version: "2"

services:
  loraserver:
    image: loraserver/loraserver:1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/loraserver:/etc/loraserver

  appserver:
    image: loraserver/lora-app-server:1
    ports:
      - 443:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/lora-app-server:/etc/lora-app-server

#  gatewaybridge:
#    image: loraserver/lora-gateway-bridge:2
#    ports:
#      - 1700:1700/udp
#    volumes:
#      - ./configuration/lora-gateway-bridge:/etc/lora-gateway-bridge
  
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
    ports:
      - 6379
    image: redis:4-alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/mqtt/config:/mosquitto/config
